trigger:
  - main   # or your required branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: NodeTool@0
    displayName: 'Set up Node.js'
    inputs:
      versionSpec: '18'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      if [ -f package.json ] && grep -q "\"test\":" package.json; then
        npm test || true
      else
        echo "No tests defined"
      fi
    displayName: 'Run tests'
    continueOnError: true

  - script: |
      if [ -f package.json ] && grep -q "\"build\":" package.json; then
        npm run build
      else
        echo "No build script found"
      fi
    displayName: 'Build application'
